spring:
  application:
    name: salary-management

  datasource:
    url: jdbc:sqlite:salary.db
    driver-class-name: org.sqlite.JDBC
    username: "admin"
    password: "1234"

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate          # Very important – let Flyway manage schema
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: INFO